#!/bin/sh

echo "Deleting previous /out folder..."
rm -rf ./out
mkdir ./out
echo "Invoking pandoc for ${@}..."
pandoc in/${@}.md -o out/${@}.html --embed-resources --standalone  --filter pandoc-plantuml --css styling.css
echo "Cleaning up..."
rm -rf ./plantuml-images
echo "Generated standalone HTML file in ./out/${@}.html"
open ./out/${@}.html
