package Pedant.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Word_Constraints extends BaseConstraintsDescriptor {
  public Word_Constraints() {
    super(CONCEPTS.Word$OI);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Word$OI = MetaAdapterFactory.getConcept(0xe1654c1208bf4d54L, 0x9998af58f6362837L, 0x59c371a1e9b64cc9L, "Pedant.structure.Word");
  }
}
