package plantmps.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import jetbrains.mps.workbench.action.ActionAccess;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.actionSystem.CommonDataKeys;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.plugins.projectplugins.ProjectPluginManager;
import java.awt.datatransfer.Clipboard;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;

public class CopyPlantUMLSource_Action extends BaseAction {
  private static final Icon ICON = IconContainer.ICON_a0_2;

  public CopyPlantUMLSource_Action() {
    super("Copy PlantUML Source", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setActionAccess(ActionAccess.UNDO_PROJECT);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    {
      Project p = event.getData(CommonDataKeys.PROJECT);
      if (p == null) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    SVGViewer_Tool content = event.getData(CommonDataKeys.PROJECT).getComponent(ProjectPluginManager.class).getTool(SVGViewer_Tool.class);
    String s = content.getPlantUMLSource();
    Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
    StringSelection selection = new StringSelection(s);
    clip.setContents(selection, null);
  }
}
