package plantmps.plugin.plugin;

/*Generated by MPS */

import javax.swing.Icon;
import jetbrains.mps.ide.icons.IconLoadingUtil;

public class IconContainer {
  protected static Icon ICON_a0 = IconLoadingUtil.loadIcon("vis.png", IconContainer.class);
  protected static Icon ICON_a0_0 = IconLoadingUtil.loadIcon("zoomInIcon.png", IconContainer.class);
  protected static Icon ICON_a0_1 = IconLoadingUtil.loadIcon("zoomOutIcon.png", IconContainer.class);
  protected static Icon ICON_a0_2 = IconLoadingUtil.loadIcon("puml.png", IconContainer.class);
  protected static Icon ICON_a0_3 = IconLoadingUtil.loadIcon("vis.png", IconContainer.class);
}
