package plantmps.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;
import com.intellij.openapi.actionSystem.Shortcut;
import com.intellij.openapi.actionSystem.KeyboardShortcut;
import javax.swing.KeyStroke;

public class PlantMPSKeyMap_KeymapChanges extends BaseKeymapChanges {
  public PlantMPSKeyMap_KeymapChanges() {
    // simple
    addSimpleShortcut("plantmps.plugin.plugin.VisualizeAction_Action", getShortcut("ctrl alt V"));
    // simple parameterized
    // complex
  }
  public String getScheme() {
    return "$default";
  }
  public static Shortcut getShortcut(String stroke) {
    return new KeyboardShortcut(KeyStroke.getKeyStroke(stroke), null);
  }
}
