package plantmps.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.plugins.actions.BaseKeymapChanges;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class Plugin_ApplicationPlugin extends BaseApplicationPlugin {
  private final PluginId myId = PluginId.getId("plantmps.plugin");

  public Plugin_ApplicationPlugin() {
  }

  @NotNull
  public PluginId getId() {
    return myId;
  }

  public void createGroups() {
    // actions w/o parameters
    addAction(new CopyPlantUMLSource_Action());
    addAction(new VisualizeAction_Action());
    addAction(new ZoomIn_Action());
    addAction(new ZoomOut_Action());
    // groups
    addGroup(new Toolbargroup_ActionGroup(this));
    addGroup(new VisualizeActionGroup_ActionGroup(this));
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(VisualizeActionGroup_ActionGroup.ID, "jetbrains.mps.ide.editor.actions.EditorPopup_ActionGroup", null);
  }
  public List<BaseKeymapChanges> initKeymaps() {
    List<BaseKeymapChanges> res = ListSequence.fromList(new ArrayList<BaseKeymapChanges>());
    ListSequence.fromList(res).addElement(new MacOSX105_KeymapChanges());
    ListSequence.fromList(res).addElement(new MacOSX_KeymapChanges());
    ListSequence.fromList(res).addElement(new PlantMPSKeyMap_KeymapChanges());
    return res;
  }
}
