package plantmps.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class Toolbargroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "plantmps.plugin.plugin.Toolbargroup_ActionGroup";

  public Toolbargroup_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("Toolbargroup", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    Toolbargroup_ActionGroup.this.addAction("plantmps.plugin.plugin.ZoomIn_Action");
    Toolbargroup_ActionGroup.this.addAction("plantmps.plugin.plugin.ZoomOut_Action");
    Toolbargroup_ActionGroup.this.addSeparator();
    Toolbargroup_ActionGroup.this.addAction("plantmps.plugin.plugin.CopyPlantUMLSource_Action");
  }
}
