package plantmps.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class VisualizeActionGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "plantmps.plugin.plugin.VisualizeActionGroup_ActionGroup";

  public VisualizeActionGroup_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("VisualizeActionGroup", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    VisualizeActionGroup_ActionGroup.this.addAction("plantmps.plugin.plugin.VisualizeAction_Action");
  }
}
